=== JairTorres1003/JT-View-Exports-SVG/nls.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON schema for nls in package View Exports SVG extension for Visual Studio Code",
  "type": "object",
  "properties": {
    "extension.title": {
      "type": "string",
      "description": "The title of the extension",
      "default": "View Exports SVG"
    },
    "extension.description": {
      "type": "string",
      "description": "The description of the extension",
      "default": "‚ú® 'View Exports SVG' is a Visual Studio Code extension designed to streamline the process of accessing and utilizing SVG icons. With this extension, you can effortlessly explore and search for SVG icons within your project, simplifying the task of finding and integrating them into your project."
    },
    "extension.commands.showMenu.title": {
      "type": "string",
      "description": "The title of the command to show the menu",
      "default": "View Exports SVG üîç"
    },
    "extension.config.assetsPath.title": {
      "type": "string",
      "description": "The title of the configuration to store the paths of analyzed files that have SVG icons",
      "default": "Assets Path"
    },
    "extension.config.assetsPath.description": {
      "type": "string",
      "description": "The description of the configuration to store the paths of analyzed files that have SVG icons",
      "default": "An array to store the paths of analyzed files that have SVG icons. This allows for quick access to them from the webview, serving as shortcuts."
    },
    "extension.config.ignoreDirectories.title": {
      "type": "string",
      "description": "The title of the configuration to store the pattern of directories to ignore when analyzing files for SVG icons",
      "default": "Ignore Directories"
    },
    "extension.config.ignoreDirectories.description": {
      "type": "string",
      "description": "The description of the configuration to store the pattern of directories to ignore when analyzing files for SVG icons",
      "default": "An array to store the pattern of directories to ignore when analyzing files for SVG icons.\nDefault:\n**/.git\n**/.github\n**/.husky\n**/.idea\n**/.idx\n**/.vscode*\n**/build\n**/coverage\n**/dist\n**/node_modules\n**/out"
    },
    "extension.config.lastScanDate.title": {
      "type": "string",
      "description": "The title of the configuration to store the date of the last scan of the workspace for SVG icons",
      "default": "Last Scan Date"
    },
    "extension.config.lastScanDate.description": {
      "type": "string",
      "description": "The description of the configuration to store the date of the last scan of the workspace for SVG icons",
      "default": "The date of the last scan of the workspace for SVG icons."
    },
    "extension.config.defaultIconProperties.title": {
      "type": "string",
      "description": "The title of the configuration to store the default properties to apply to SVG icons",
      "default": "Default Icon Properties"
    },
    "extension.config.defaultIconProperties.description": {
      "type": "string",
      "description": "The description of the configuration to store the default properties to apply to SVG icons",
      "default": "Default properties to apply to SVG icons when they do not have a property defined or when the extension does not find it."
    },
    "extension.config.showNotExportedIcons.title": {
      "type": "string",
      "description": "The title of the configuration to indicate whether or not to show icons that are not being exported",
      "default": "Show Not Exported Icons"
    },
    "extension.config.showNotExportedIcons.description": {
      "type": "string",
      "description": "The description of the configuration to indicate whether or not to show icons that are not being exported",
      "default": "Indicates whether or not to show icons that are not being exported."
    },
    "extension.config.groupPatterns.title": {
      "type": "string",
      "description": "The title of the configuration to store an array of patterns to group icon files",
      "default": "Group Patterns"
    },
    "extension.config.groupPatterns.description": {
      "type": "string",
      "description": "The description of the configuration to store an array of patterns to group icon files",
      "default": "An array of patterns to group icon files. Each pattern requires an 'item' (the pattern) and a 'value (the group name).\nExample:\n| item | value |\n| --- | --- |\n| ** | All Icons |\n| **/Flag* | Flags |\n| **/Symbol*.{js, jsx} | Symbols |"
    },
    "extension.config.recentIcons.showIcons.title": {
      "type": "string",
      "description": "The title of the configuration to indicate whether or not to show recent icons",
      "default": "Show Recent Icons"
    },
    "extension.config.recentIcons.showIcons.description": {
      "type": "string",
      "description": "The description of the configuration to indicate whether or not to show recent icons",
      "default": "Indicates whether or not to show the most recently accessed icons."
    },
    "extension.config.recentIcons.limitShowIcons.title": {
      "type": "string",
      "description": "The title of the configuration to store the limit of recent icons to show",
      "default": "Limit Show Recent Icons"
    },
    "extension.config.recentIcons.limitShowIcons.description": {
      "type": "string",
      "description": "The description of the configuration to store the limit of recent icons to show",
      "default": "The maximum number of recent icons to show."
    }
  },
  "required": [
    "extension.title",
    "extension.description",
    "extension.commands.showMenu.title",
    "extension.config.assetsPath.title",
    "extension.config.assetsPath.description",
    "extension.config.ignoreDirectories.title",
    "extension.config.ignoreDirectories.description",
    "extension.config.lastScanDate.title",
    "extension.config.lastScanDate.description",
    "extension.config.defaultIconProperties.title",
    "extension.config.defaultIconProperties.description",
    "extension.config.showNotExportedIcons.title",
    "extension.config.showNotExportedIcons.description",
    "extension.config.groupPatterns.title",
    "extension.config.groupPatterns.description",
    "extension.config.recentIcons.showIcons.title",
    "extension.config.recentIcons.showIcons.description",
    "extension.config.recentIcons.limitShowIcons.title",
    "extension.config.recentIcons.limitShowIcons.description"
  ]
}

=== JairTorres1003/JT-View-Exports-SVG/package.nls.ru.json
{
  "extension.title": "–ü—Ä–æ—Å–º–æ—Ç—Ä –≠–∫—Å–ø–æ—Ä—Ç–æ–≤ SVG",
  "extension.description": "‚ú® '–ü—Ä–æ—Å–º–æ—Ç—Ä –≠–∫—Å–ø–æ—Ä—Ç–æ–≤ SVG' - —ç—Ç–æ —Ä–∞—Å—à–∏—Ä–µ–Ω–∏–µ –¥–ª—è Visual Studio Code, –ø—Ä–µ–¥–Ω–∞–∑–Ω–∞—á–µ–Ω–Ω–æ–µ –¥–ª—è —É–ø—Ä–æ—â–µ–Ω–∏—è –ø—Ä–æ—Ü–µ—Å—Å–∞ –¥–æ—Å—Ç—É–ø–∞ –∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è SVG-–∏–∫–æ–Ω–æ–∫. –° —ç—Ç–∏–º —Ä–∞—Å—à–∏—Ä–µ–Ω–∏–µ–º –≤—ã –º–æ–∂–µ—Ç–µ –ª–µ–≥–∫–æ –∏—Å—Å–ª–µ–¥–æ–≤–∞—Ç—å –∏ –∏—Å–∫–∞—Ç—å SVG-–∏–∫–æ–Ω–∫–∏ –≤ –≤–∞—à–µ–º –ø—Ä–æ–µ–∫—Ç–µ, —É–ø—Ä–æ—â–∞—è –∑–∞–¥–∞—á—É –∏—Ö –Ω–∞—Ö–æ–∂–¥–µ–Ω–∏—è –∏ –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏–∏ –≤ –ø—Ä–æ–µ–∫—Ç.",
  "extension.commands.showMenu.title": "–ü—Ä–æ—Å–º–æ—Ç—Ä –≠–∫—Å–ø–æ—Ä—Ç–æ–≤ SVG üîç",
  "extension.config.assetsPath.title": "–ü—É—Ç—å –∫ —Ä–µ—Å—É—Ä—Å–∞–º",
  "extension.config.assetsPath.description": "–ú–∞—Å—Å–∏–≤ –¥–ª—è —Ö—Ä–∞–Ω–µ–Ω–∏—è –ø—É—Ç–µ–π –∫ –ø—Ä–æ–∞–Ω–∞–ª–∏–∑–∏—Ä–æ–≤–∞–Ω–Ω—ã–º —Ñ–∞–π–ª–∞–º, —Å–æ–¥–µ—Ä–∂–∞—â–∏–º SVG-–∏–∫–æ–Ω–∫–∏. –≠—Ç–æ –ø–æ–∑–≤–æ–ª—è–µ—Ç –±—ã—Å—Ç—Ä–æ –ø–æ–ª—É—á–∏—Ç—å –∫ –Ω–∏–º –¥–æ—Å—Ç—É–ø –∏–∑ –≤–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–∞, —Å–ª—É–∂–∞ —è—Ä–ª—ã–∫–∞–º–∏.",
  "extension.config.ignoreDirectories.title": "–ò–≥–Ω–æ—Ä–∏—Ä–æ–≤–∞—Ç—å –ö–∞—Ç–∞–ª–æ–≥–∏",
  "extension.config.ignoreDirectories.description": "–ú–∞—Å—Å–∏–≤ –¥–ª—è —Ö—Ä–∞–Ω–µ–Ω–∏—è —à–∞–±–ª–æ–Ω–æ–≤ –∫–∞—Ç–∞–ª–æ–≥–æ–≤, –∫–æ—Ç–æ—Ä—ã–µ –Ω—É–∂–Ω–æ –∏–≥–Ω–æ—Ä–∏—Ä–æ–≤–∞—Ç—å –ø—Ä–∏ –∞–Ω–∞–ª–∏–∑–µ —Ñ–∞–π–ª–æ–≤ –Ω–∞ –Ω–∞–ª–∏—á–∏–µ SVG-–∏–∫–æ–Ω–æ–∫.\n–ü–æ —É–º–æ–ª—á–∞–Ω–∏—é:\n**/.git\n**/.github\n**/.husky\n**/.idea\n**/.idx\n**/.vscode*\n**/build\n**/coverage\n**/dist\n**/node_modules\n**/out",
  "extension.config.lastScanDate.title": "–î–∞—Ç–∞ –ü–æ—Å–ª–µ–¥–Ω–µ–≥–æ –°–∫–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏—è",
  "extension.config.lastScanDate.description": "–î–∞—Ç–∞ –ø–æ—Å–ª–µ–¥–Ω–µ–≥–æ —Å–∫–∞–Ω–∏—Ä–æ–≤–∞–Ω–∏—è —Ä–∞–±–æ—á–µ–π –æ–±–ª–∞—Å—Ç–∏ –Ω–∞ –Ω–∞–ª–∏—á–∏–µ SVG-–∏–∫–æ–Ω–æ–∫.",
  "extension.config.defaultIconProperties.title": "–°–≤–æ–π—Å—Ç–≤–∞ –ò–∫–æ–Ω–æ–∫ –ü–æ –£–º–æ–ª—á–∞–Ω–∏—é",
  "extension.config.defaultIconProperties.description": "–°–≤–æ–π—Å—Ç–≤–∞ –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é, –ø—Ä–∏–º–µ–Ω—è–µ–º—ã–µ –∫ SVG-–∏–∫–æ–Ω–∫–∞–º, –µ—Å–ª–∏ —É –Ω–∏—Ö –Ω–µ –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–æ —Å–≤–æ–π—Å—Ç–≤–æ –∏–ª–∏ –µ—Å–ª–∏ —Ä–∞—Å—à–∏—Ä–µ–Ω–∏–µ –µ–≥–æ –Ω–µ –Ω–∞—Ö–æ–¥–∏—Ç.",
  "extension.config.showNotExportedIcons.title": "–ü–æ–∫–∞–∑—ã–≤–∞—Ç—å –ù–µ—ç–∫—Å–ø–æ—Ä—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–µ –ò–∫–æ–Ω–∫–∏",
  "extension.config.showNotExportedIcons.description": "–£–∫–∞–∑—ã–≤–∞–µ—Ç, –ø–æ–∫–∞–∑—ã–≤–∞—Ç—å –ª–∏ –∏–∫–æ–Ω–∫–∏, –∫–æ—Ç–æ—Ä—ã–µ –Ω–µ —ç–∫—Å–ø–æ—Ä—Ç–∏—Ä—É—é—Ç—Å—è.",
  "extension.config.groupPatterns.title": "–®–∞–±–ª–æ–Ω—ã –ì—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏",
  "extension.config.groupPatterns.description": "–ú–∞—Å—Å–∏–≤ —à–∞–±–ª–æ–Ω–æ–≤ –¥–ª—è –≥—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∏ —Ñ–∞–π–ª–æ–≤ –∏–∫–æ–Ω–æ–∫. –ö–∞–∂–¥—ã–π —à–∞–±–ª–æ–Ω —Ç—Ä–µ–±—É–µ—Ç '—ç–ª–µ–º–µ–Ω—Ç' (—à–∞–±–ª–æ–Ω) –∏ '–∑–Ω–∞—á–µ–Ω–∏–µ' (–∏–º—è –≥—Ä—É–ø–ø—ã).\n–ü—Ä–∏–º–µ—Ä:\n| –≠–ª–µ–º–µ–Ω—Ç | –ó–Ω–∞—á–µ–Ω–∏–µ |\n| --- | --- |\n| ** | –í—Å–µ –ò–∫–æ–Ω–∫–∏ |\n| **/Flag* | –§–ª–∞–≥–∏ |\n| **/Symbol*.{js, jsx} | –°–∏–º–≤–æ–ª—ã |",
  "extension.config.recentIcons.showIcons.title": "–ü–æ–∫–∞–∑—ã–≤–∞—Ç—å –ù–µ–¥–∞–≤–Ω–∏–µ –ò–∫–æ–Ω–∫–∏",
  "extension.config.recentIcons.showIcons.description": "–£–∫–∞–∑—ã–≤–∞–µ—Ç, –ø–æ–∫–∞–∑—ã–≤–∞—Ç—å –ª–∏ –ø–æ—Å–ª–µ–¥–Ω–∏–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–Ω—ã–µ –∏–∫–æ–Ω–∫–∏.",
  "extension.config.recentIcons.limitShowIcons.title": "–õ–∏–º–∏—Ç –ü–æ–∫–∞–∑–∞ –ù–µ–¥–∞–≤–Ω–∏—Ö –ò–∫–æ–Ω–æ–∫",
  "extension.config.recentIcons.limitShowIcons.description": "–ú–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ—Å–ª–µ–¥–Ω–∏—Ö –∏–∫–æ–Ω–æ–∫ –¥–ª—è –ø–æ–∫–∞–∑–∞."
}

=== JairTorres1003/JT-View-Exports-SVG/package.nls.de.json
{
  "extension.title": "SVG-Exporte anzeigen",
  "extension.description": "‚ú® 'View Exports SVG' ist eine Visual Studio Code-Erweiterung, die entwickelt wurde, um den Zugriff und die Verwendung von SVG-Icons zu optimieren. Mit dieser Erweiterung k√∂nnen Sie m√ºhelos SVG-Icons in Ihrem Projekt erkunden und suchen, was die Aufgabe vereinfacht, sie zu finden und in Ihr Projekt zu integrieren.",
  "extension.commands.showMenu.title": "SVG-Exporte anzeigen üîç",
  "extension.config.assetsPath.title": "Assets-Pfad",
  "extension.config.assetsPath.description": "Ein Array zum Speichern der Pfade analysierter Dateien, die SVG-Icons enthalten. Dies erm√∂glicht einen schnellen Zugriff auf sie aus dem Webview heraus und dient als Verkn√ºpfungen.",
  "extension.config.ignoreDirectories.title": "Verzeichnisse ignorieren",
  "extension.config.ignoreDirectories.description": "Ein Array zum Speichern der Muster von Verzeichnissen, die beim Analysieren von Dateien nach SVG-Icons ignoriert werden sollen.\nStandard:\n**/.git\n**/.github\n**/.husky\n**/.idea\n**/.idx\n**/.vscode*\n**/build\n**/coverage\n**/dist\n**/node_modules\n**/out",
  "extension.config.lastScanDate.title": "Letztes Scan-Datum",
  "extension.config.lastScanDate.description": "Das Datum des letzten Scans des Arbeitsbereichs nach SVG-Icons.",
  "extension.config.defaultIconProperties.title": "Standard-Icon-Eigenschaften",
  "extension.config.defaultIconProperties.description": "Standard-Eigenschaften, die auf SVG-Icons angewendet werden, wenn sie keine definierte Eigenschaft haben oder wenn die Erweiterung sie nicht findet.",
  "extension.config.showNotExportedIcons.title": "Nicht exportierte Icons anzeigen",
  "extension.config.showNotExportedIcons.description": "Gibt an, ob nicht exportierte Icons angezeigt werden sollen oder nicht.",
  "extension.config.groupPatterns.title": "Gruppenmuster",
  "extension.config.groupPatterns.description": "Ein Array von Mustern zum Gruppieren von Icon-Dateien. Jedes Muster erfordert ein 'Element' (das Muster) und einen 'Wert' (den Gruppennamen).\nBeispiel:\n| Element | Wert |\n| --- | --- |\n| ** | Alle Icons |\n| **/Flag* | Flaggen |\n| **/Symbol*.{js, jsx} | Symbole |",
  "extension.config.recentIcons.showIcons.title": "Neueste Icons anzeigen",
  "extension.config.recentIcons.showIcons.description": "Gibt an, ob die zuletzt verwendeten Icons angezeigt werden sollen oder nicht.",
  "extension.config.recentIcons.limitShowIcons.title": "Anzeige der neuesten Icons begrenzen",
  "extension.config.recentIcons.limitShowIcons.description": "Die maximale Anzahl der zuletzt verwendeten Icons, die angezeigt werden sollen."
}

=== JairTorres1003/JT-View-Exports-SVG/package.nls.zh_TW.json
{
  "extension.title": "查看導出 SVG",
  "extension.description": "✨ '查看導出 SVG' 是一個 Visual Studio Code 擴展，旨在簡化訪問和使用 SVG 圖標的過程。使用此擴展，您可以輕鬆地在項目中瀏覽和搜索 SVG 圖標，簡化了在項目中查找和集成它們的任務。",
  "extension.commands.showMenu.title": "查看導出 SVG 🔍",
  "extension.config.assetsPath.title": "資產路徑",
  "extension.config.assetsPath.description": "一個數組，用於存儲包含 SVG 圖標的已分析文件的路徑。這允許從 webview 快速訪問它們，作為快捷方式。",
  "extension.config.ignoreDirectories.title": "忽略目錄",
  "extension.config.ignoreDirectories.description": "一個數組，用於存儲在分析文件以查找 SVG 圖標時要忽略的目錄模式。\n默認：\n**/.git\n**/.github\n**/.husky\n**/.idea\n**/.idx\n**/.vscode*\n**/build\n**/coverage\n**/dist\n**/node_modules\n**/out",
  "extension.config.lastScanDate.title": "最後掃描日期",
  "extension.config.lastScanDate.description": "工作區中最後一次掃描 SVG 圖標的日期。",
  "extension.config.defaultIconProperties.title": "默認圖標屬性",
  "extension.config.defaultIconProperties.description": "當 SVG 圖標沒有定義屬性或擴展未找到時，應用於 SVG 圖標的默認屬性。",
  "extension.config.showNotExportedIcons.title": "顯示未導出的圖標",
  "extension.config.showNotExportedIcons.description": "指示是否顯示未導出的圖標。",
  "extension.config.groupPatterns.title": "分組模式",
  "extension.config.groupPatterns.description": "用於分組圖標文件的模式數組。每個模式都需要一個 '元素'（模式）和一個 '值'（組名）。\n示例：\n| 元素 | 值 |\n| --- | --- |\n| ** | 所有圖標 |\n| **/Flag* | 國旗 |\n| **/Symbol*.{js, jsx} | 符號 |",
  "extension.config.recentIcons.showIcons.title": "顯示最近的圖標",
  "extension.config.recentIcons.showIcons.description": "指示是否顯示最近訪問的圖標。",
  "extension.config.recentIcons.limitShowIcons.title": "限制顯示最近的圖標",
  "extension.config.recentIcons.limitShowIcons.description": "要顯示的最近圖標的最大數量。"
}

=== JairTorres1003/JT-View-Exports-SVG/package.nls.ja.json
{
  "extension.title": "SVGエクスポートを表示",
  "extension.description": "✨ 'SVGエクスポートを表示' は、SVGアイコンへのアクセスと利用を効率化するために設計されたVisual Studio Code拡張機能です。この拡張機能を使用すると、プロジェクト内のSVGアイコンを簡単に探索して検索し、プロジェクトに統合するタスクを簡素化できます。",
  "extension.commands.showMenu.title": "SVGエクスポートを表示 🔍",
  "extension.config.assetsPath.title": "アセットパス",
  "extension.config.assetsPath.description": "SVGアイコンを持つ解析されたファイルのパスを格納する配列です。これにより、ウェブビューからそれらに素早くアクセスでき、ショートカットとして機能します。",
  "extension.config.ignoreDirectories.title": "ディレクトリを無視",
  "extension.config.ignoreDirectories.description": "SVGアイコンのファイルを解析する際に無視するディレクトリのパターンを格納する配列です。\nデフォルト:\n**/.git\n**/.github\n**/.husky\n**/.idea\n**/.idx\n**/.vscode*\n**/build\n**/coverage\n**/dist\n**/node_modules\n**/out",
  "extension.config.lastScanDate.title": "最終スキャン日",
  "extension.config.lastScanDate.description": "ワークスペースのSVGアイコンの最終スキャン日。",
  "extension.config.defaultIconProperties.title": "デフォルトアイコンプロパティ",
  "extension.config.defaultIconProperties.description": "SVGアイコンにプロパティが定義されていない場合や拡張機能がそれを見つけられない場合に適用するデフォルトのプロパティ。",
  "extension.config.showNotExportedIcons.title": "エクスポートされていないアイコンを表示",
  "extension.config.showNotExportedIcons.description": "エクスポートされていないアイコンを表示するかどうかを示します。",
  "extension.config.groupPatterns.title": "グループパターン",
  "extension.config.recentIcons.showIcons.title": "最近のアイコンを表示",
  "extension.config.groupPatterns.description": "アイコンファイルをグループ化するためのパターンの配列です。各パターンには 「項目」（パターン）と 「値」（グループ名）が必要です。\n例:\n| 項目 | 値 |\n| --- | --- |\n| ** | すべてのアイコン |\n| **/Flag* | フラグ |\n| **/Symbol*.{js, jsx} | シンボル |",
  "extension.config.recentIcons.showIcons.description": "最近アクセスしたアイコンを表示するかどうかを示します。",
  "extension.config.recentIcons.limitShowIcons.title": "最近のアイコンの表示制限",
  "extension.config.recentIcons.limitShowIcons.description": "表示する最近のアイコンの最大数。"
}
